services:
  server:
    build:
      context: .
    stdin_open: true
    tty: true
    environment:
      - TOKEN=${TOKEN}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - CARDS_TABLE_NAME=${CARDS_TABLE_NAME}
